
apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: solace-direct-message-tcp
  namespace: solace
  labels:
    app: solace-direct-message-tcp
spec:
  selector:
    matchLabels:
      app: solace-direct-message-tcp
  replicas: 1
  template:
    metadata:
      labels:
        app: solace-direct-message-tcp
    spec:
      containers:
      - name: solace-direct-message-tcp
        image: solace-direct-message-app:latest  # or just image: solace-direct-message-app
        #image: registry.k8s.io/solace-direct-message-app:e2e  # or just image: solace-direct-message-app
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 500m
            memory: 512Mi
        ports:
        - containerPort: 8080