version: '2'
services:
  topics-ui:
    image: landoop/kafka-topics-ui
    environment:
      KAFKA_REST_PROXY_URL: rest-proxy:8082
      PROXY: "true"
      # # Users are managed within Lenses. Here you can change the superuser username:
      # LENSES_SECURITY_USER: admin
      # # Users are managed within Lenses. Here you can change the superuser password:
      # LENSES_SECURITY_PASSWORD: admin
    ports:
      - 8000:8000
    networks:
      - confluent_default                




  data-ui:
    image: lensesio/fast-data-dev:latest
    environment:
      ADV_HOST: "data-ui"
      BROKER_PORT: "9092"
      REST_PORT: "8082"
      # # Users are managed within Lenses. Here you can change the superuser username:
      # LENSES_SECURITY_USER: admin
      # # Users are managed within Lenses. Here you can change the superuser password:
      # LENSES_SECURITY_PASSWORD: admin
    ports:
      - 2111:2181
      - 3030:3030
      - 1111:8081
      - 2222:8082
      - 3333:8083
      - 9581:9581
      - 9582:9582
      - 9583:9583
      - 9584:9584
      - 9585:9585
      - 9999:9092


    networks:
      - confluent_default     


networks:
  confluent_default:
    external: true      
