version: '2.3'
services:
  mysql:
    image: mysql:5.7.19
    ports:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql/scripts:/docker-entrypoint-initdb.d
    command: [--ssl=0]
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-uroot", "-proot"]
      interval: 120s
      timeout: 300s
      retries: 30
      start_period: 300s
  am-analytics:
    image: wso2/wso2am-analytics-worker:2.6.0
    ports:
      - "9091:9091"
      - "9444:9444"
    healthcheck:
      test: ["CMD", "nc", "-z","localhost", "9091"]
      interval: 120s
      timeout: 300s
      start_period: 300s
      retries: 30
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./apim-analytics:/home/wso2carbon/wso2-config-volume
  is-as-km:
    image: wso2/wso2is-km:5.7.0
    healthcheck:
      test: ["CMD", "curl", "-k", "-f", "https://localhost:9443/carbon/admin/login.jsp"]
      interval: 120s
      timeout: 300s
      start_period: 300s
      retries: 30
    depends_on:
      mysql:
        condition: service_healthy
      am-analytics:
        condition: service_healthy
    volumes:
      - ./is-as-km:/home/wso2carbon/wso2-config-volume
    ports:
      - "9765:9763"
      - "9445:9443"
  api-manager:
    image: wso2/wso2am:2.6.0
    healthcheck:
      test: ["CMD", "curl", "-k", "-f", "https://localhost:9443/carbon/admin/login.jsp"]
      interval: 120s
      timeout: 300s
      start_period: 300s
      retries: 30
    depends_on:
      mysql:
        condition: service_healthy
      am-analytics:
        condition: service_healthy
      is-as-km:
        condition: service_healthy
    volumes:
      - ./apim:/home/wso2carbon/wso2-config-volume
   #   - /home/ec2-user/authenticationendpoint.war:/home/wso2carbon/wso2am-2.6.0/repository/deployment/server/webapps/authenticationendpoint.war
    ports:
      - "9763:9763"
      - "9443:9443"
      - "8280:8280"
      - "8243:8243"