version: '3.8'

services:
  jobmanager:
    image: flink:1.18.1
    ports:
      - "8099:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager        
#     volumes:
#       - /tmp/flink:/opt/flink/usrlib
    networks:
      - confluent_default

  taskmanager:
    image: flink:1.18.1
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2
#     volumes:
#       - /tmp/flink:/opt/flink/usrlib
    networks:
      - confluent_default  

  sql-client:
    image: flink:1.18.1
    command: bash -c 'bin/sql-client.sh'
    depends_on:
      - jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        rest.address: jobmanager
    networks:
      - confluent_default                


networks:
  confluent_default:
    external: true      
