kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: jenkins-sc
#provisioner: kubernetes.io/no-provisioner
#provisioner: hostpath-provisioner-runner
provisioner: nfs-storage
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
reclaimPolicy: Retain
