

#DEFAULT LOGIN
#USER=superadmin
#PASSWORD=welcometoklaw

apiVersion: v1
kind: Service
metadata:
  name: klaw-core
spec:
  selector:
    app: klaw-core
  ports:
    - name: http
      port: 9097
      targetPort: 9097
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: klaw-core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: klaw-core
  template:
    metadata:
      labels:
        app: klaw-core
    spec:
      containers:
        - name: klaw-core
          image: aivenoy/klaw-core:latest
          env:
            - name: KLAW_UIAPI_SERVERS
              value: http://klaw-core:9097
            - name: KLAW_CLUSTERAPI_URL
              value: http://klaw-cluster-api:9343
            - name: KLAW_CLUSTERAPI_ACCESS_BASE64_SECRET
              value: "dGhpcyBpcyBhIHNlY3JldCB0byBhY2Nlc3MgY2x1c3RlcmFwaQ=="
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:h2:file:/klaw/klawprodb;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;MODE=MySQL;CASE_INSENSITIVE_IDENTIFIERS=TRUE;"
          # volumeMounts:
          #   - name: klaw-data
          #     mountPath: /klaw
      # volumes:
      #   - name: klaw-data
      #     persistentVolumeClaim:
      #       claimName: klaw-data

#       docker run -d -t -i \
# -e KLAW_CLUSTERAPI_ACCESS_BASE64_SECRET="dGhpcyBpcyBhIHNlY3JldCB0byBhY2Nlc3MgY2x1c3RlcmFwaQ==" \
# -p 9343:9343 \
# --name klaw-cluster-api aivenoy/klaw-cluster-api:nightly --add-host host.docker.internal:host-gateway \
# && docker run -d -t -i \
# -e KLAW_UIAPI_SERVERS=http://host.docker.internal:9097 -e KLAW_CLUSTERAPI_ACCESS_BASE64_SECRET="dGhpcyBpcyBhIHNlY3JldCB0byBhY2Nlc3MgY2x1c3RlcmFwaQ==" \
# -e KLAW_QUICKSTART_ENABLED=true \
# -e SPRING_DATASOURCE_URL="jdbc:h2:file:/klaw/klawprodb;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;MODE=MySQL;CASE_INSENSITIVE_IDENTIFIERS=TRUE;" \
# -p 9097:9097 --name klaw-core aivenoy/klaw-core:nightly \
# && docker run -d -t -i -p 2181:2181 --add-host host.docker.internal:host-gateway \
# -e ALLOW_ANONYMOUS_LOGIN=yes --name klaw-zookeeper bitnami/zookeeper:3.8 \
# && docker run -d -t -i -p 9092:9092 --add-host host.docker.internal:host-gateway \
# -e KAFKA_CFG_ZOOKEEPER_CONNECT=host.docker.internal:2181 -e ALLOW_PLAINTEXT_LISTENER=yes \
# -e KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://host.docker.internal:9092 \
# --name klaw-kafka bitnami/kafka:3.3 \
# && docker run -d -t -i -p 8081:8081 --add-host host.docker.internal:host-gateway \
# -e SCHEMA_REGISTRY_KAFKA_BROKERS=PLAINTEXT://host.docker.internal:9092 \
# --name klaw-schema-registry bitnami/schema-registry:latest
---
apiVersion: v1
kind: Service
metadata:
  name: klaw-cluster-api
spec:
  selector:
    app: klaw-cluster-api
  ports:
    - name: http
      port: 9343
      targetPort: 9343
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: klaw-cluster-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: klaw-cluster-api
  template:
    metadata:
      labels:
        app: klaw-cluster-api
    spec:
      containers:
        - name: klaw-cluster-api
          image: aivenoy/klaw-cluster-api:latest
          env:
            - name: KLAW_CLUSTERAPI_ACCESS_BASE64_SECRET
              value: "dGhpcyBpcyBhIHNlY3JldCB0byBhY2Nlc3MgY2x1c3RlcmFwaQ=="
      #     volumeMounts:
      #       - name: klaw-data
      #         mountPath: /klaw
      # volumes:
      #   - name: klaw-data
      #     persistentVolumeClaim:
      #       claimName: klaw-data
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: klaw-data
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Gi
#   storageClassName: hostpath